# Generated by Django 6.0.6 on 2026-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Сотрудник"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Суперпользователь"),
        ),
    ]
