# Generated by Django 6.0.6 on 2026-06-29 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_owner_lesson_owner"),
        ("users", "0007_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID цены",
                max_length=255,
                null=True,
                verbose_name="ID цены",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID продукта",
                max_length=255,
                null=True,
                verbose_name="ID продукта",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
