# Generated by Django 6.0.6 on 2026-07-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_owner_lesson_owner"),
        ("users", "0008_alter_subscription_options_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subscription",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.lesson",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course", "lesson")},
        ),
    ]
