# Generated by Django 6.0.6 on 2026-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=150,
                null=True,
                verbose_name="Cсылка на видео",
            ),
        ),
    ]
